### ISSUE TITLE
Address dependency management issues

### ISSUE THREAD

**Issue by notmessenger** [ciena-blueplanet/ember-spread#37]
to `^5.0.1`

**Comment by juwara0** [comment]
Closed via #34

**Comment by notmessenger** [comment]
https://github.com/ciena-blueplanet/ember-prop-types/issues/153 **MUST** be resolved before this issue can be addressed.  Some of the individual tasks _may_ be able to be worked on before the completion of the dependent issue.  If doing so indicate which tasks have been completed by checking them off in the list below, as well as adding a comment to this issue indicating the name of the branch you have pushed to this repo so that work can completed once the dependent task has been addressed.

* Tasks that have the text _"(verified)"_ after them are ones that have either already been tested or are known to work.  This does not mean that you should not still be cautious but you likely don't have to do as much research as you might initially be inclinded to.
* None of the tasks make a determination of whether a dependency should be a **dependency** or **devDependency** _UNLESS_ otherwise stated.  Even then it is prudent to confirm this indicator.
* All dependencies should float to `^` unless the directions in the tasks indicate otherwise.

**NPM**

* [ ] remove ember-cli-chai (verified) (note that ember-frost-test is now providing it at 0.4.3 so _may_ encounter issues)
* [ ] remove ember-cli-mocha (verified) (note that ember-frost-test is now providing it at 0.14.4 so _may_ encounter issues)
* [ ] remove ember-sinon (verified) (note that ember-frost-test is now providing it at ^0.7.0 so _may_ encounter issues)
* [ ] remove ember-test-utils (verified) (note that ember-frost-test is now providing it at ^7.0.2 so *will* encounter linting failures)
* [ ] remove sinon-chai
* [ ] remove chai-jquery
* [ ] install ember-frost-test (verified)
* [ ] pin ember-cli-code-coverage to 0.3.12
* [ ] verify ember-cli-code-coverage is tied into "npm run test" script
* [ ] verify "tests/config/coverage.js" and not "config/coverage.js"
* [ ] pin ember-cli-htmlbars-inline-precompile to 0.3.12
* [ ] downgrade and pin ember-code-snippet to 1.7.0
* [ ] update ember-hook to 1.4.2
* [ ] determine whether ember-hook needs to be a **dependency**
* [ ] determine **dependencies** vs **devDependencies**

**BOWER**
* [x] n/a

**Comment by notmessenger** [comment]
JIRA: FROST-583

**Comment by notmessenger** [comment]
In-progress changes have been pushed to the `Issue37` branch.

Before PR can be opened as a **PATCH** against the `Issue37` branch:

* [ ] `ember-frost-test@4.0.0` must be released
  * https://github.com/ciena-frost/ember-frost-test/pull/42
* [ ] `ember-prop-types@6.0.0` must be released
* [ ] `ember-cli-frost-blueprints@5.0.0` must be released
